package com.itzdgc.webservice.serviceinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2018-10-15T16:32:17.248+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sysHi", targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", className = "com.itzdgc.webservice.serviceinterface.SysHi")
    @ResponseWrapper(localName = "sysHiResponse", targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", className = "com.itzdgc.webservice.serviceinterface.SysHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sysHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllCats", targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", className = "com.itzdgc.webservice.serviceinterface.GetAllCats")
    @ResponseWrapper(localName = "getAllCatsResponse", targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", className = "com.itzdgc.webservice.serviceinterface.GetAllCatsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.itzdgc.webservice.serviceinterface.Data getAllCats();

    @WebMethod
    @RequestWrapper(localName = "getCatsByUser", targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", className = "com.itzdgc.webservice.serviceinterface.GetCatsByUser")
    @ResponseWrapper(localName = "getCatsByUserResponse", targetNamespace = "http://serviceInterface.webservice.itzdgc.com/", className = "com.itzdgc.webservice.serviceinterface.GetCatsByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.itzdgc.webservice.serviceinterface.Cat> getCatsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.itzdgc.webservice.serviceinterface.User arg0
    );
}
